### ISSUE TITLE
inappropriate images

### ISSUE THREAD

**Issue by JamieKnight** [markboulton/child-phone-contract#2]
Great idea. 

While reading through this rule kept out at me. I’ve worked with vulnerable people on this topic and we started recommend the following sort of advice.

Things like:

* simpler terms
* prompt to get help
* reminder that asking for help won’t result in punishment.

So something like: “If you see inappropriate images of anything or anyone else; delete them, close the tab, delete the app.”

To something like: “If you see anything that scares you, or makes you uncomfortable speak to Mum and Dad. You won’t be punished for asking for help”

**Comment by markboulton** [comment]
Thanks Jamie. Your suggestion on images is Incorporated into latest version and I'll look at editing the other points too. Really good advice. Thank you!

**Comment by snorkers** [comment]
The word 'punished' is not helpful. Change 'You won't be punished for help' to 'Don't be afraid to ask for help'
